name: 构建

启用: [推送,工作流调度]

jobs:
构建:
运行于: ubuntu-latest
步骤:
      - 使用: actions/checkout@v3
      - 使用: actions/setup-java@v3
        with:
java版本: '17'
      - 运行: chmod +x gradlew && ./gradlew assembleDebug
      - 使用: actions/upload-artifact@v3
        with:
名称: APK
          path: app/build/outputs/apk/debug/app-debug.apk
